### ISSUE TITLE
read artwork from audio file

### ISSUE THREAD

**Issue by inglesuniversal** [derhuerst/read-audio-tags#7]
I copied your sample code and I got this from a test local file...

{
  encoder: 'Lavf56.25.101',
  title: 'We Are The Champions - Remastered 2011',
  artist: 'Queen',
  album: 'News Of The World (2011 Remaster)',
  album_artist: 'Queen',
  disc: '1',
  track: '2'
}

How can I extract the image data too?

Thanks

**Comment by derhuerst** [comment]
AFAICT this is not possible with `ffprobe`, which is being used underneath this library. But with `ffmpeg` you should be able to extract it: https://stackoverflow.com/questions/25680542/how-to-get-album-image-from-mp3-file-using-ffmpeg-in-php

**Comment by inglesuniversal** [comment]
ok Got it... and I tested it and worked fine... Do you happen to know how to implement that on a browser? To be able to scale images within the webpage in Javascript?

Regards

**Comment by derhuerst** [comment]
> Do you happen to know how to implement that on a browser? To be able to scale images within the webpage in Javascript?

Extract the artwork from a media file? Or resize the image?

Keep in mind that `read-audio-tags` doesn't work in the browser, only in Node.

**Comment by inglesuniversal** [comment]
Well actually... The command I found extracted the image and resized it to 250x250px from its original size of about 640p.

ffmpeg -i "Queen - We Are The Champions.mp3" -filter:v scale=-2:300 -an "Queen - We Are The Champions.jpg"

Now, even if it works in node.js I have read of some libraries like https://requirejs.org/ ... Does this kind of script allows me to use node in the browser? Are you familiar with that? Thanks for your valuable help.

**Comment by derhuerst** [comment]
> Now, even if it works in node.js I have read of some libraries like https://requirejs.org/ ... Does this kind of script allows me to use node in the browser? Are you familiar with that? Thanks for your valuable help.

I am familiar with it. JavaScript libraries only work in the browser if they don't use Node.js-/server-specific APIs, such as file system, executing commands etc. This library spawns the `ffprobe` command line tool, so it doesn't work in the browser.

There are ways to get tools like `ffprobe` running in the browser, but it's a lot of work; you will have to custom-compile their source code into [WebAssembly](https://webassembly.org) or [asm.js](http://asmjs.org).

Your best bet is to find a pure-JS [ID3](https://en.wikipedia.org/wiki/ID3) parsing library: https://www.npmjs.com/search?q=id3
